### ISSUE TITLE
Q: 2.3.3的AS里没有 debugger 栏

### ISSUE THREAD

**Issue by wbo4958** [tiann/android-native-debug#1]
![image](https://user-images.githubusercontent.com/1320706/27572921-70f4cedc-5b41-11e7-8c43-a6d72ce70ad5.png)

**Comment by tiann** [comment]
@wbo4958 https://stackoverflow.com/questions/42966471/no-debugger-tab-in-edit-configurations-android-studio-2-3

**Comment by wbo4958** [comment]
赞！ 搞定了！ Thx
