### ISSUE TITLE
可以选择真机中的随意进程，然后调试Android源码中c++的部分吗

### ISSUE THREAD

**Issue by bmax121** [tiann/android-native-debug#4]

**Comment by tiann** [comment]
@pickastar root了才可以调试任意进程。

然后，如果真机修改了源码，那只能汇编调试。

**Comment by bmax121** [comment]
那也就是可以了，就是没看会如何操作。。。

**Comment by tiann** [comment]
说清楚具体是哪一步不会，不然我能帮你什么呢？

**Comment by bmax121** [comment]
源码应该放在新建工程哪个目录下面，要做什么设置吗，还有那个选择进程的界面是怎么出来的。并不是做Android的，也没怎么用过AndroidStudio，所以可能问的比较low，，谢谢你的帮助。

**Comment by tiann** [comment]
1. 源码没有特殊的目录要求，只需要设置映射关系，文中也提到了。
2. 选择进程的界面，是Android Studio自带的调试功能，建议你先能正常调试自己的App的代码，再尝试调试系统源码。

**Comment by bmax121** [comment]
有空我再捣鼓捣鼓，搞不明白再来，多谢大侠🤗

**Comment by bmax121** [comment]
是这样的，所以用 adb am start 启动一个app，然后再附加调试，可是打的断点没断到，程序就已经运行起来了。断点代码就在app启动时运行，该怎么办

**Comment by tiann** [comment]
`adb shell am set-debug-app -w --persistent <你的包名>`

这样启动的App的时候，系统会等待debugger attched才会继续执行你App的代码。

**Comment by bmax121** [comment]
不是 adb shell am start 吗，只是想调试下 so 的加载过程，attach 上去断点没断 so 都加载完了，还提示
![image](https://user-images.githubusercontent.com/12316019/30894186-cfb67c60-a374-11e7-948e-6e47be206847.png)

**Comment by tiann** [comment]
你先去查查我发的这句话什么意思。

既然知道是时机晚了，要么把attach时机提前，要么把so加载延后。

**Comment by bmax121** [comment]
还是没明白，am set-debug-app 跟 am start 效果类似啊，attach 的时候程序就启动了，没法做源码，符号的设置代码就执行完了，有什么地方可以向IDA一样设置挂起吗

**Comment by tiann** [comment]
没懂你这句话什么意思。

你无非是想调试so的加载过程，但是attach的时机比so加载的时机晚。所以要么你想办法把attach的时机提前，比如我说的那个set-debug-app的方法；要么你就延迟so的加载，attach之后再调试，比如写个按钮，点击之后开始加载so，这样就能在点按钮之前attach上。而这并不是什么技术问题。

**Comment by bmax121** [comment]
你说的对，是我表述的有问题，我其实想知道的是被加壳的 so  的信息，并不是 so 的加载过程。。。看来这么调试还是有难度。多谢你的帮助！
