### ISSUE TITLE
运行这个DEMO，一直报错

### ISSUE THREAD

**Issue by asus8881** [tiann/android-native-debug#6]
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage

----
一直报这个错误，怎么处理下呢

**Comment by tiann** [comment]
这个demo不是拿来运行的，只是一个简单的project，让AS可以找到调试的符号。

**Comment by asus8881** [comment]
谢谢，是这样我使用真机调试，点debug按钮后，就出现上述错误了，进入不到调试阶段

**Comment by asus8881** [comment]
我自己新建了个工程，CMAKE的问题解决了，可能是因为版本不匹配。可是还有个问题就是我的编译产物没有libart.so,zip，这个是怎么来的呢？

**Comment by tiann** [comment]
这个是我编译Android系统源码得到的编译产物，这个工程不是拿来编译的
